services:
  redis:
    image: redis:7
    container_name: mlc-1048-redis
    ports:
      - "6379:6379"

  mlc-1048:
    build: 
      context: .
      dockerfile: Containerfile
    container_name:  mlc-1048
    ports:
      - "3000:3000"
    env_file:
      - .env